### ISSUE TITLE
Depends on FirePHP even in prod

### ISSUE THREAD

**Issue by MugeSo** [bearsunday/BEAR.Package#103]
BEAR.Package know depends on FirePHP because use it in BEAR\Package\Provide\ApplicationLogger\ResourceLog\WritersProvider.
The `WriterProvider` is injected in BEAR\Package\Provide\ApplicationLogger\ApplicationLoggerModule, which is installed by default.

However, in `composer.json`, require statement is for "dev".

**Comment by koriym** [comment]
I'm aware of that situation. A current version didn't provide their own 'prod' log writer. User need to bind their own application logger in 'prod'. but I'm currently working(yes, I should raise issue) for that II will give default application logger (maybe Null) in next release.

**Comment by koriym** [comment]
fixed at https://github.com/koriym/BEAR.Package/commit/5a0e1e9b614a1f5c52a7f16368d283780ec4ca2e
