### ISSUE TITLE
Tiwg problem

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#106]
`feature/more-twig`ブランチで`/blog/posts`がうまく表示されず困ってます。

アプリケーションテンプレートには$resourceという値でリソースオブジェクト全体がアサインされます。

[$this->templateEngineAdapter->assign('resource', $resourceObject);](https://github.com/koriym/BEAR.Package/blob/a399121bcd4c9fe8f0bfea273d5f828135cce9b9/src/Provide/ResourceView/TemplateEngineRenderer.php#L54)

ところがTwigでその参照ができません

https://github.com/koriym/BEAR.Package/blob/feature/more-twig/apps/Demo.Sandbox/src/Resource/App/Blog/Posts.twig#L10

同じフォルダにあるSmartyでは参照できています。

https://github.com/koriym/BEAR.Package/blob/feature/more-twig/apps/Demo.Sandbox/src/Resource/App/Blog/Posts.tpl

何が問題でしょうか？　bodyには値ではなくリソースリクエストオブジェクトがアサインされています。文字列評価の__toString()でリソースアクセスを実行して値を取得します。

**Comment by MugeSo** [comment]
ArrayAccessが先に処理されてるので、`resource.body`は`$resouerce['body']`を参照しているかと思います。

https://github.com/fabpot/Twig/blob/master/lib/Twig/Template.php#L356

**Comment by MugeSo** [comment]
http://twig.sensiolabs.org/doc/templates.html#variables

**Comment by MugeSo** [comment]
でもbodyが定義されてないから`isset($resource['body'])`がfalseでプロパティ取得になるのかな。

**Comment by koriym** [comment]
情報ありがとうございます。自動生成されたテンプレートに問題？という感触持ってるのですがまだ特定できてません。

**Comment by koriym** [comment]
原因分かりました。単純なbugのようでおってcommitします。お騒がせしました！
