### ISSUE TITLE
Fail testing on develop branch since a399121

### ISSUE THREAD

**Issue by MugeSo** [bearsunday/BEAR.Package#108]
a399121bcd4c9fe8f0bfea273d5f828135cce9b9

https://travis-ci.org/koriym/BEAR.Package/jobs/17955202

**Comment by koriym** [comment]
Not sure what's wrong with this. 
Its ok with PHP 5.4.24.The earlier PHP version cause this error ?

**Comment by MugeSo** [comment]
It seems that ApplicationReflector class try to load "Demo.Sandbox\Resource\Page\Hello\World.tpl" class.

Following code returns a list of Resource Object classes including "World.tpl". 
https://github.com/koriym/BEAR.Package/blob/develop/src/Dev/Application/ApplicationReflector.php#L81-L97
