### ISSUE TITLE
web context injector

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#114]
An alternative way to get web context without pulling values from injected web context service.

``` php
    /**
     * @QueryParam(id = "id")             // $_GET['id']
     * @FormParam(title = "title")        // $_POST['tile']
     * @CookieParam(loginId = "login_id") // $_COOKIE['login_id']
     * @HeaderParam(format = "format")    // $_SERVER['format']
     */
    public function onPost($id, $title, $loginId, $format)
    {
```

pros: testability, readability. self-description, "inject everything" policy
cons: runtime cost(?)

The basic idea comes from JAX-RS. This function provided by interceptor.

**Comment by MugeSo** [comment]
How about raw entity body for HTTP PUT method and POST with non-formal mime-type?

**Comment by koriym** [comment]
These four seems fair enough to start with. But possible.

**Comment by koriym** [comment]
Plan B: "Interface as annotation"

``` php
public function onPost(QueryParam $id, FormParam $name, CookieParam $id)
{
    var_dump((string)$id);  // 1 $_GET['id']
    var_dump($cookie->value);   // 10 $_COOKIE['id']
}

```

**Comment by MugeSo** [comment]
How do you think to resolve name conflict e.g. QueryParam vs CookieParam in Plan B?

**Comment by koriym** [comment]
can't get it.  updated example helps you ?

**Comment by koriym** [comment]
but ideas here seems not so good...i don't know. I try to think more.

**Comment by MugeSo** [comment]
Oh, i got it! My bad.

**Comment by koriym** [comment]
Using interface as annotion seems interesting idea for runtime injection for Ray.Di.
But maybe not for BEAR.Resource. I close this issue.
