### ISSUE TITLE
Router 変更案

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#115]
**前提**
- BEAR.Resourceは不変
- URI設計はアプリケーションドメイン。フレームワークは特定の構造を押しつけないし、新しいルーターが紹介されても既存のものは影響を受けない。（ルーターはアプリケーションスクリプトとの契約。アプリケーションスクリプトとルーターのみ結合して他のライブラリの影響は受けない）

**解決しようとする問題**
- 各ルーターの重複機能の排除
- メソッドオーバーライドなどのWebルーティングがどうあるべきかをコンテキスト依存のインジェクタブルに
- 異なったルーターを採用しやすいように

**変更点**
- ルーターをベースのルーター＋ルーターアダプターの構成にしてアダプターは複数指定することができる。引き数の順番が優先順。

``` php
$router = new Rounter([new AuraRouterAdapter]);
$router = new Rounter([new AuraRouterAdapter, new WebRouterAdapter]);
```
- 従来の`$_GET`や`$_POST`の内容がメソッドの引き数に反映されるのは`WebRouterAdapter`
- WebRouterAdapterを使用しないと従来のMVCフレームワークのルーターの働きと同じ。（URIのパスの部分がメソッド、リソースクラス、その引き数を決定）

Routerインターフェイス=不変
Routerアダプターインターフェイス

``` php
interface RouterAdapterInterface
{
    /**
     * @param string $path
     * @param array  $globals
     *
     * @return array array [$method, $requestUri, $query]
     */
    public function match($path, array $globals = []);
}
```

**背景**

ルーターの要求はURI設計への要求であり、アプリケーションの要求です。特定のURI設計パラダイムをフレームワークが押し付けるべきではないと考えます。また現在PHPが用意するルーターも多様で、要求の異なる構成が可能です。

例えばフォームのフィールドによるメソッドオーバーライドはAPIコンテキストでサービスする場合には必要ないかもしれないし、従来のルーターの仕組みだけで構成する場合には`$_GET`がメソッドのパラーメーターになる`WebRouterAdapter`は必要ないかもしれません。ルーターやBEAR.ResourceをFATにすることなく、柔軟な機能追加/変更のための再構成が必要なのではと考えました。

 https://github.com/search?o=desc&q=php+router+&s=stars&source=cc&type=Repositories

**Comment by MugeSo** [comment]
:+1:

**Comment by koriym** [comment]
ベースルーターの生成を変更しました。コンストラクタでは`array`ではなく`RouterAdapterInterface`で依存ルーターを指定します。複数のルーターを指定するときには`Routers`ルーターを使います。

``` php
$router = new Rounter(new AuraRouterAdapter);
$router = new Rounter(new Routers([new AuraRouterAdapter, new WebRouterAdapter]);
```

**Comment by koriym** [comment]
- Webのパスをそのまま使用しクエリーを引数とする`WebRouter`, 
- `Aura v2 Router`を使用する`AuraRouter`
- 複数のルーターを使用できる`Routers`

現在、この３つのアダプターあがあります。

Symfonyルーターは旧来のまま（使用可能）、Aura v1 Routerは依存Aura Routerが変わったので利用できなくなりました。

Aura v1 Routerを利用可能にするにはAuraModule一式をPackagistで独立したパッケージにして管理する必要があります。

**Comment by koriym** [comment]
Aura v1とSymfonyルーターを一旦レポジトリから削除する案もあります。

**目的**
開発リソースとメンテナンスコストの削減のため

**互換性**
レポジトリから削除されたこれらのライブラリを継続使用するためには旧来の`BEAR\Package\Router`をBEAR.Package以外のディレクトリ等に退避しauto loader指定して、必要に応じて`composer.json`を編集すれば利用可能です。

**Adapter\SymfonyRouter**
本来はこれを用意するのが良いと思います。

**Comment by MugeSo** [comment]
`Routers`クラスですが、他の箇所を考慮すると`RouterCollection`のほうが良い気がしますがいかがでしょう。

**Comment by koriym** [comment]
それが良いと思います。

**Comment by MugeSo** [comment]
テストクラスのファイル名がRoutersのままの様です。

**Comment by koriym** [comment]
既存のSymfonyルーターとAura(v1)ルーターを`develop`リポジトリから削除から削除しました。
これらをご継続利用したい場合があれば相談して下さい。
