### ISSUE TITLE
サブディレクトリでの運用

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#129]
> http://example.jp/bear/ のようなサブディレクトリで運用することは簡単にできますでしょうか？
> https://twitter.com/kenji_s/status/472179902578692096

https://github.com/koriym/BEAR.DemoApps/blob/develop/Demo.Sandbox/bootstrap/contexts/dev.php#L62
ここで取得した`$pagePath`の先頭の`/bear/`を取り除けばパスの変換ができます。contexts/*.php`はアプリケーションスクリプトといってアプリケーションのシークエンスを記述します。

`Demo.Helloworld`のアプリケーションスクリプトもご覧下さい。これで外部のHTTPからBEARのリソースに変換する仕組みがよくわかると思います。
https://github.com/koriym/BEAR.DemoApps/blob/develop/Demo.Helloworld/var/www/index.php

以下は参考までに

**方法１） /bearだけのリソースをつくる**

リソースの作成は`Resource/Bear/`にアセットファイル（スタティックファイル）は`{$appDir}/bear/`に。

**方法3）URI Mapper**

例えばこの`api.php`用のスクリプトは`Demo.Sandbox`の`appリソース`を`/api/`をルートにサービスしています。(webで`/blog/posts`だったら`/api/blog/posts`になります) URI Mapperの動作を変更するにはURI Mapperの記述が必要です。
https://github.com/koriym/BEAR.DemoApps/blob/develop/Demo.Sandbox/bootstrap/contexts/api.php

**方法4）ルーターの使用**

**Comment by kenjis** [comment]
ありがとうございます。

ブラウザからページを表示することはできました。

あと、ページ中のリンクのパスに `/bear` を追加しないといけないようです。

**Comment by koriym** [comment]
自分自身がこのような要求を持った事があまりないのですが、どのような場合の話でしょうか？

**Comment by kenjis** [comment]
http://example.jp/bear/ で Sandbox を稼働させた場合、URL は http://example.jp/bear/ ですが、
ページ内のリンクは `a href="/blog/posts"` のようになっているため、

http://example.jp/blog/posts

となってしまい、クリックしてもアクセスできません。

http://example.jp/bear/blog/posts

になる必要があります。

**Comment by koriym** [comment]
"ルートを想定してアプリケーションをつくってそれを違うパスで運用する” ということでしょうか？

**Comment by kenjis** [comment]
要求としては、

http://example.jp/
http://example.jp/bear/

どちらでも運用できる（簡単にURLを変更できる）ようにしたいということになりますでしょうか。

まあ、単純に Sandbox をサブディレクトリで動かせないかと思っただけですが。そうできれば、VirtualHostを用意せずに気軽に今あるサーバ上で動かしてみることもできますので。

**Comment by koriym** [comment]
なるほど。開発でwebで確認ならbuilt in webサーバーもあり、私はこちらを利用してます。お勧めです。また可能な限りコンソールでwebと同じ操作が可能なようにしたいと思っています。webテストなしでアプリケーションのテストカバレッジ100パーセントに到達出来るのが理想です。

プロダクションでは最も変更のないものがURLという仮定を持っていますが、必要に応じてアプリケーションで実装するのは可能です。ただ他の機能同様に固定した仕組みを持つより望む機能を**適切な制約**を持って実装できるということに注力しています。
