### ISSUE TITLE
Warning: pack(): Type H: illegal hex digit -

### ISSUE THREAD

**Issue by kenjis** [bearsunday/BEAR.Package#136]
In my Linux 32bit environment, sometimes this error occurs.

> Warning: pack(): Type H: illegal hex digit - in .../vendor/ray/di/src/CompilationLogger.php on line 108

I reload the page several times, it sometimes may disappear, sometimes not disappear. Very  strange.

Backtrace:

> [Wed Jun 25 14:24:25 2014] ErrorException(E_WARNING: pack(): Type H: illegal hex digit -) in /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/ExceptionHandler.php on line 25 (get page://self/blog/posts)
> # 0 [internal function]: BEAR\Package\Dev\Dev->BEAR\Package\Dev{closure}(2, 'pack(): Type H:...', '/home/kenji/wor...', 108, Array)
> # 1 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/CompilationLogger.php(108): pack('H*', '-1080435773')
> # 2 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/CompilationLogger.php(114): Ray\Di\CompilationLogger->Ray\Di{closure}('00000000297d65c...')
> # 3 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/DependencyFactory.php(66): Ray\Di\CompilationLogger->getObjectHash(Object(Demo_Sandbox_Resource_App_Blog_Posts_cc436baec58dbc6a06237a589e2e39d8RayAop))
> # 4 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/CompilationLogger.php(155): Ray\Di\DependencyFactory->__construct(Object(Demo_Sandbox_Resource_App_Blog_Posts_cc436baec58dbc6a06237a589e2e39d8RayAop), Array, Array, Object(Ray\Di\CompilationLogger))
> # 5 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/CompilationLogger.php(79): Ray\Di\CompilationLogger->build('Demo\Sandbox\Re...', Object(Demo_Sandbox_Resource_App_Blog_Posts_cc436baec58dbc6a06237a589e2e39d8RayAop), Array, Array)
> # 6 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/Injector.php(227): Ray\Di\CompilationLogger->log('Demo\Sandbox\Re...', Array, Array, Object(Demo_Sandbox_Resource_App_Blog_Posts_cc436baec58dbc6a06237a589e2e39d8RayAop), Object(Ray\Aop\Bind))
> # 7 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/DiCompiler.php(142): Ray\Di\Injector->getInstance('Demo\Sandbox\Re...')
> # 8 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/DiCompiler.php(188): Ray\Di\DiCompiler->compile('Demo\Sandbox\Re...')
> # 9 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/ray/di/src/DiCompiler.php(159): Ray\Di\DiCompiler->recompile('Demo\Sandbox\Re...')
> # 10 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Adapter/App.php(79): Ray\Di\DiCompiler->getInstance('Demo\Sandbox\Re...')
> # 11 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Factory.php(70): BEAR\Resource\Adapter\App->get('app://self/blog...')
> # 12 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Resource.php(156): BEAR\Resource\Factory->newInstance('app://self/blog...')
> # 13 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Resource.php(202): BEAR\Resource\Resource->newInstance('app://self/blog...')
> # 14 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/apps/Demo.Sandbox/src/Resource/Page/Blog/Posts.php(24): BEAR\Resource\Resource->uri('app://self/blog...')
> # 15 [internal function]: Demo\Sandbox\Resource\Page\Blog\Posts->onGet()
> # 16 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Invoker.php(138): call_user_func_array(Array, Array)
> # 17 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Resource.php(291): BEAR\Resource\Invoker->invoke(Object(BEAR\Resource\Request))
> # 18 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/vendor/bear/resource/src/Resource.php(274): BEAR\Resource\Resource->invoke()
> # 19 /home/kenji/work/bear-sunday/bear-sunday-blog-tutorial/apps/Demo.Sandbox/bootstrap/contexts/dev.php(71): BEAR\Resource\Resource->request()
> # 20 {main}

```
# Required
[OK] PHP: 5.5.11
[OK] Vendor install
# Optional
[NG] APC: 
[NG] uri_template: 
# Develop
[NG] Xdebug: 
[OK] PDO-Sqlite: 1.0.1
[NG] xhprof: 

BEAR.Sunday env check: [OK] 
```

**Comment by koriym** [comment]
here ?

``` php
$shortHash = function ($data, $algo = 'CRC32') {
            return strtr(rtrim(base64_encode(pack('H*', $algo($data))), '='), '+/', '-_');
        };
```

Weird. But I will remove this part anyway. Thanks for the report,  I've never seen before.

**Comment by kenjis** [comment]
I've found the cause.

> Because PHP's integer type is signed many crc32 checksums will result in negative integers on 32bit platforms. On 64bit installations all crc32() results will be positive integers though.
> So you need to use the "%u" formatter of sprintf() or printf() to get the string representation of the unsigned crc32() checksum in decimal format. 
> http://www.php.net/crc32

Below code works fine.

``` php
$shortHash = function ($data, $algo = 'CRC32') {
            return strtr(rtrim(base64_encode(pack('H*', sprintf('%u', $algo($data)))), '='), '+/', '-_');
        };
```

**Comment by koriym** [comment]
wow !

**Comment by koriym** [comment]
move to https://github.com/koriym/Ray.Di/issues/71
