### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by kenjis** [bearsunday/BEAR.Package#141]
We need CSRF protection.

First of all, we need a place to store tokens. Session?

So we need Session Library.

**Comment by koriym** [comment]
@jingu Session + CSRF すでに実装してなかったかな？

**Comment by jingu** [comment]
前実装した時はAura.InputとAura.Sessionでやりました。
Aura.InputのCSRF対策は非常に簡素な内容で、特定のコンポーネントへの結合もありません。それ故使いやすかったと思います。

I chose Aura.Input and Aura.form.
Aura.Input has the minimum CSRF attacks protection feature, Having no any coupling component with others . It makes easy to use, I think.

**Comment by koriym** [comment]
@jingu It would be nice if we see demo code on Demo.Sandbox ? I know @kenjis and others will agree with me  ! :)

**Comment by kenjis** [comment]
It is very basic functionality. So I think BEAR.Package should have at least one implementation.

**Comment by koriym** [comment]
**"very basic"** is a good reason we choose.

Even if we need more functional libs, it should be self independent and decoupled library which can be used from non BEAR.Sunday system.

**Comment by koriym** [comment]
@kenjis I close this issue. But feel free to re-open.
