### ISSUE TITLE
AuraForm has name="submit" element. It prevents jQuery submit()

### ISSUE THREAD

**Issue by kenjis** [bearsunday/BEAR.Package#155]
AuraForm requires a tag like `<input type="submit" name="submit" ...>`

https://github.com/koriym/BEAR.Package/blob/develop/src/Module/Form/AuraForm/AuraFormTrait.php#L71

But `name="submit"` or `id="submit"` prevent jQuery `$(form).submit()` function from working fine.

See http://dqn.sakusakutto.jp/2013/04/jquery_form_submit.html

So I want to change the value of name attribute.

**Comment by koriym** [comment]
@kenjis Thanks. Seems better to change. Any proposal ?

**Comment by kenjis** [comment]
How about `_submit`?

One more thing. If we send form with `$(form).submit()`, the data of `type="submit"` element will not be sent.

How about below? This can detect all POST submission.

``` diff
--- a/src/Module/Form/AuraForm/AuraFormTrait.php
+++ b/src/Module/Form/AuraForm/AuraFormTrait.php
@@ -70,13 +70,12 @@ trait AuraFormTrait
      */
     private function getSubmit()
     {
-        if (isset($_POST['submit'])) {
+        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
             return [$_POST, true];
-        } elseif (isset($_GET['submit'])) {
+        } elseif (isset($_GET['_submit'])) {
             return [$_GET, true];
         }
         return [[], false];
-
     }

     /**
```

**Comment by koriym** [comment]
It seems good.
