### ISSUE TITLE
BEAR.Sunday 1.0

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#159]
# BEAR.Sunday 1.0 alpha

BEAR.Sunday 1.0の概要です。
## はじめに

以下の２つのコンセプトに注力するために、量的なものを大胆に削っています。
- HTTPアプリケーションのためのアーキテクチャ
- アプリケーション制約を提供する
### Package versions

セマンティックバージョニングです。
メジャーバージョンはそれぞれあがり、BCブレイクが一部あります。

Ray.Di `2.0`
Ray.Aop `2.0`
BEAR.Resource `1.0`
BEAR.Sunday `1.0`
BEAR.Package `1.0`
BEAR.Skeleton `1.0`
### 検討
- `AppMeta` - 名前はこれでいいか？
- 最低限のHTML表現をサポートすべきか？、その場合(Twig, Aura.View, Moustache 

一旦`1.0`がリリースされたら`2.0`を出さないつもりで（つまりBCブレイクなしで）継続するつもりでいます。
### Framework Extension

フレームワークの機能拡張を４つにしぼりました。アプリケーション、ルーター、リプレゼンテーション、トランスファーの４つです。それぞれ、**構成**、**入力**、**表現**、**出力**に対応します。

つまりDIとAOPでアプリケーションを構成して(App)、リソースのリクエストを受け取り(Router)、アプリケーション状態を変更してその表現を求め（Representation）、レスポンスとして出力（Transfer)します。

REST (Representational State Transfer)をそのままフレームワークとして拡張ポイント
- [Application](https://github.com/koriym/BEAR.Sunday/tree/develop-2/src/Extension/Application)
- [Router](https://github.com/koriym/BEAR.Sunday/tree/develop-2/src/Extension/Router)
- [Representation](https://github.com/koriym/BEAR.Sunday/tree/develop-2/src/Extension/Representation)
- [Transfer](https://github.com/koriym/BEAR.Sunday/tree/develop-2/src/Extension/Transfer)
### Context Module

コンテキストに応じてアプリケーションの振舞いは変わります。
- Hal
- Api
- Cli
- Prod

https://github.com/koriym/BEAR.Package/tree/develop-2/src/Context
### Plugin Module

コンテキストによらないアプリケーションの拡張機能です。現在はAuraルーターと [HAL](http://stateless.co/hal_specification.html) 関連のみがあります。
- Web Router
- Aura Router
- Router Collection
- Hal Render / Transger

https://github.com/koriym/BEAR.Package/tree/develop-2/src/Module
### Application

アプリケーションのメタ情報はそれぞれの定数(tmp_dir)などではなく、１つのオブジェクトにまとめられました。同様に各種の設定値は文字列として扱われるのではなくて、オブジェクトのプロパティとして扱われることが望まれます。

アプリケーションブートストラップは基本的にはコンテキストによらず同一です。

スケルトンはよりシンプルになりました。同時に複数のアプリケーションが機能します。
- Application meta info - [AppMeta](https://github.com/koriym/BEAR.Package/blob/develop-2/src/AbstractAppMeta.php)
- Application factory [Bootstrap](https://github.com/koriym/BEAR.Package/blob/develop-2/src/Bootstrap.php)
- Application skeleton [BEAR.Skeleton](https://github.com/koriym/BEAR.Skeleton)
- Application bootstrap script [bootstrap.php](https://github.com/koriym/BEAR.Skeleton/blob/develop-2/bootstrap/bootstrap.php)
### Ray.Aop
- [MOD] カスタムMatcher
- [ADD] namespaceの継承
- [MOD] 速度、安定性
### Ray.Di
- [MOD] インターセプターのバインドがオブジェクトではなくクラス名に。束縛順を気にする必要がなくなりました。
- [DEL] AbstractModule::requestInjection();
- [DEL] DI logger
- [DEL] DI compiler
### BEAR.Resource
- [DEL] シグナルパラメーター
- [DEL] httpアダプター(guzzle)
- [DEL] sync request
### BEAR.Sunday
- [MOD] アノテーション、Extention、Provideの整理
- [DEL] Aura WebContext
### BEAR.Package
- [DEL] Devツール
- [DEL] DB, Form, Sessionなどのライブラリ
- [DEL] HTMl出力
- [DEL] デモアプリ
- [DEL] アプリケーションリフレクター
- [ADD] コンテキストによるアプリケーションのデコレーション
### 検討点
- `AppMeta` - 名前はこれでよいか？ (AppPropertiesやAppConfigはどうか）- OK
- `bootsrap.php` - 名前はこれでよいか？ (app_scriptやrun.phpはどうか）- OK
- 最低限のHTMLコンテキストを含めるべきではないか？ - NO
  - そうならTwig ? Aura.View ? moustache ? 岩崎さんがTwigModuleを作成
- 最低限のDAOを含めるべきではないか？ - Ex.Packageで
  - そうならDoctrine Dbal ? Aura.Sql ?  - Aura.Sql基本で、しかしオラクル用にDbalも
- アプリケーションレイアウトはこれでよいか？ - OK
- `定数`ファイルを完全に外してよいか？ - OK
- `0.x`にあった`script/instance.php`ファイルは要らないか？- 要検討
- アプリケーションスケルトンの`tests`の内容 - 要検討

**Comment by koriym** [comment]
検討点どうでしょうか？ ping @mackstar @zingoo @zukimochi

**Comment by zukimochi** [comment]
Ex.PackageがあるのでBEAR.Packageにはテンプレートエンジン含まれて無くて良いのではと思います。
READMEにBEAR.Package、Ex.Packageの位置づけの説明とEx.Packageへのリンクを付けておくのはどうでしょうか。

BEARの場合設定値などはDIして使う場合がほとんどで、Moduleで一回だけ読まれて終わりなのではないかと思います。
そうなるとあえてファイルに切り出す意義が薄れる様に感じます。
Moduleのディレクトリ全体がある意味設定ファイルと考えてしまうのはどうでしょうか。

**Comment by koriym** [comment]
> READMEにBEAR.Package、Ex.Packageの位置づけの説明とEx.Packageへのリンクを付けておく

いいですね

> そうなるとあえてファイルに切り出す意義が薄れる様に感じます。

configの事ですよね。モジュールに引数与える形を基本にしていみます。

**Comment by koriym** [comment]
パフォーマンスのために`BEAR.QueryRespository`を追加

**Comment by koriym** [comment]
https://github.com/koriym/BEAR.Sunday/issues/52 に続く
