### ISSUE TITLE
./{yourAppName} only accepts upper camel case at this moment?

### ISSUE THREAD

**Issue by remore** [bearsunday/BEAR.Package#16]
While README.md tells like this,

```
$ php composer.phar create-project -s dev --dev bear/skeleton ./{yourAppName}
```

At /{yourAppName} parameter It seems "MyApp" works fine but "myApp" doesn't.

The error I've encountered today was:

```
[hoge@hostname public]# pwd
/tmp/bear/apps/myApp/public
[hoge@hostname public]# php api.php get /
500 Internal Server Error
x-exception-class: ["BEAR\\Package\\Provide\\Application\\Exception\\InvalidMode"]
x-exception-message: ["Invalid mode [Api], [MyApp\\Module\\ApiModule] class unavailable"]
x-exception-code-file-line: ["(0) \/tmp\/bear\/src\/BEAR\/Package\/Provide\/Application\/ApplicationFactory.php:51"]
x-exception-previous: ["-"]
x-exception-id: ["e500-7cfe3"]
x-exception-id-file: ["\/tmp\/bear\/scripts\/data\/log\/e500-7cfe3.log"]
cache-control: ["no-cache"]
date: ["Sun, 17 Feb 2013 16:24:34 GMT"]
[BODY]
Internal error occurred (e500-7cfe3)
```

Just my guess but it looks weird that x-exception-message uses upper camel case for application name.

**Comment by koriym** [comment]
Created folder name become name space root as application name. (Sandbox, Skeleton or Blog)
It should be follow PSR-0,  "myApp" is not proper name.

It may something wrong in post install script ?

**Comment by remore** [comment]
Understood.

**Comment by koriym** [comment]
Post install script should change the folder name from myApp  to MyApp.
issue moved to https://github.com/koriym/BEAR.Skeleton/issues/4
