### ISSUE TITLE
ApiRouter not found error at ApiModule

### ISSUE THREAD

**Issue by madapaja** [bearsunday/BEAR.Package#161]
`bootstrap/api.php` を実行した場合に `ApiRouter` が見つからないため、エラーとなります。

`BEAR.Package/src/Context/ApiModule.php` で、`use BEAR\Package\Provide\Router\ApiRouter;` として `ApiRouter` が参照されていますが、パッケージ内に該当のクラスがありません。

**Comment by koriym** [comment]
完全にミスですね。ありがとうございます。
