### ISSUE TITLE
アプリケーションとフレームワークのレイアウト

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#164]
http://qiita.com/koriym/items/3f060df9b5c854a42a9b#comment-a4db45f8f14043f88f83 からの転載です。
## 

すみません、1.0 に関する質問です。とても初歩的な質問で恐縮ですが。

（1）
1.0 における BEAR.Package と BEAR.Skeleton の関係・使い分けがよく分かっていないのですが、どう考えるとよいでしょうか？
0.13 のときは、BEAR.Package で BEAR.Sunday 本体や必要なライブラリを設置し、その中（apps/）に BEAR.Skeleton で作ったアプリケーションのひな形をおく、というようにしていましたが、1.0 の BEAR.Skeleton では composer install すると vendor など必要なファイル一式が揃い、BEAR.Package とあまり変わらないように見え、どちらをベースに作っていくといいか、迷っております。

（2）
BEAR.Package 0.13 では apps/ 以下に Myvendor.Myproject などのアプリケーションを入れていました（ https://bearsunday.github.io/manual/en/install.html 等の説明を見ながら）が、BEAR.Sunday 1.0 では docs/ がその場所を引き継いだという理解で正しいでしょうか？
最初、 docs/ というとヘルプファイル置き場的なディレクトリかなと思っていたのですが ^ ^;;

**Comment by koriym** [comment]
まず、「ファイルレイアウトは固定されていない」これが基本になります。autoloadができれば何処でも良いです。アプリケーションもライブラリも全て"Vendor.Pacackage"名で表されるパッケージです。

> 1.0 の BEAR.Skeleton では composer install すると vendor など必要なファイル一式が揃い、BEAR.Package とあまり変わらないように見え、どちらをベースに

基本となるアプリケーションをメインのプロジェクトとして、その他は全て依存としてインストールするのはどうでしょうか。つまりBEAR.SkeletonでインストールしたアプリAのvendor/にBEAR.Packageや他のアプリケーションが格納されます。

> BEAR.Sunday 1.0 では docs/ がその場所を引き継いだという理解で正しいでしょうか？

これは間違ってます。"デモアプリ"として`docs/demo/`を使用しているだけです。デモアプリを参考資料(doc)にということです。

**Comment by kilica** [comment]
アドバイスありがとうございます！

> まず、「ファイルレイアウトは固定されていない」これが基本になります。autoloadができれば何処でも良いです。アプリケーションもライブラリも全て"Vendor.Pacackage"名で表されるパッケージです。

了解です。

> 基本となるアプリケーションをメインのプロジェクトとして、その他は全て依存としてインストールするのはどうでしょうか。つまりBEAR.SkeletonでインストールしたアプリAのvendor/にBEAR.Packageや他のアプリケーションが格納されます。

なるほど、そういうレイアウトでもいいんですね。
いただいたアドバイスを元に考えてみます。
ありがとうございました。

​

**Comment by koriym** [comment]
> 基本となるアプリケーションをメインのプロジェクトとして、その他は全て依存

「迷ったらルールの少ない方に」原則にも合致すると思います！

**Comment by koriym** [comment]
複数のアプリケーションや共通ライブラリを同時に編集したい場合もあると思います。BEARもResource、Sunday、Packageと依存が複数あり、結合してる部分に変更が生じる度に（良いやり方がわからず）面倒でしたが以下の方法で快適になりました。
- `composer install` は`prefer-source`でgitで落として、`vendor/`下も編集対象にする。
- ライブラリはcomposer.lockを除く。*1

*1 アプリケーションでもリリースtag切るまでそれでいいかもしれません。

**Comment by kenjis** [comment]
> ライブラリはcomposer.lockを除く

これはどういう効果というかメリットがあるのでしょうか？

**Comment by koriym** [comment]
特定ファイルではなくて（`branch-alias`の）バージョンに依存するようになります。依存に変更があっても利用レポジトリに変更が不要です。

**Comment by iteman** [comment]
`composer.lock`はそのパッケージの開発自体でしか参照されないので、その開発において特定バージョンに縛るメリットはあまりないでしょう。一般的には`composer.json`において下限を保証し、場合によっては上限も設定という運用が行われていると思います。

一方アプリケーションにおいては動作保証を行ったバージョンを固定するメリットがあります。

**Comment by koriym** [comment]
@iteman ありがとうございます＾＾

**Comment by koriym** [comment]
こんな記事を見つけました。

On Project Structure; or, The Framework/App Is Not Special
http://paul-m-jones.com/archives/6029

この記事をみて変更したわけではないのですが、考えはほぼ同じです。
Appフォルダという特別な場所をつくるのではなく、ごく普通にパッケージのファイルとして配置します。
