### ISSUE TITLE
コレクションパターンを手軽に扱うアイデア

### ISSUE THREAD

**Issue by ritalin** [bearsunday/BEAR.Package#209]
## TL;DR

_\BEAR\Package\Provide\Router\HttpMethodParams_ の _getOverRideMethod()_ メソッドを _unsafeMethod()_ からではなく、 _get()_ から行うようにして欲しい
## 概要

BEAR.Sundayでコレクションパターンを実現するためには、現状、 _ResourceObject.get()_ で、条件分岐させる、
または [bear/aura-router-module](https://github.com/bearsunday/BEAR.AuraRouterModule)を利用して、ルーティングでコレクション用ResourceObjectとアイテム用ResourceObjectに振り分けるかのいずれかとなります。

ひとつのリソースを扱うために複数のResourceObjectを用意するのは煩雑であり、できればひとつのResourceObjectのメッソドで振り分けることが望まれます。
## 案

以前、 @koriym 方でコレクションは _GetList_ 、アイテムは _Get_ でキックするというアイデアを出されてましたが、理由は忘れましたが没にした言われた記憶があります。

個人的にも、外部に _GetList_ を露出させるのはあまりうれしいことではなく、また使う側としてもできればGetで適宜振り分けてくれた方がよいでしょう。
しかし、うまく実現できれば、ひとつのResourceObjectでコレクションパターンを表現できるため、そのまま没にするのはもったいなく思います。

bear/aura-router-module の力を借り、コレクションの場合は、GetListに、アイテムの場合はGetそのままスルーするよう、ルート設定を記述すれば、負担をフレームワークに押付けることなく実現できるように思えます。

しかし、ルートマッチング後のHTTPメソッドをAuraRouterで差し替えることはできないため、少し手段を講じる必要があります。
BEAR.SundayのRequestオブジェクトを作成する際のHTTPメソッドの決定は、HttpMethodParamsで行っており、そこでは __method_ パラメータで指定される代替メソッドも受け入れるようになっていると見受けられます。
マッチング後のパラメータとして、 __method='GetList'_ を与えてあげることで解決できそうに思えます。
しかし、現状、代替メソッドは、Getメソッドでは適用されず、Postメソッドからとなっています。

そこで、代替メソッドの適用( _getOverRideMethod_ )を Router\HttpMethodParams.get() から適用する変更のみで、コレクションパターンをひとつのResourceObjectで取り扱うことができるようなると思われます。

ルート設定は、相変わらず複数指定しますが、それ自体ルーティングのカタログとしての側面もあるため、この点については特に問題ないと思われます。

**Comment by ritalin** [comment]
このアイデアは、コレクションパターンとして提示しましたが、
一歩進めて新規追加のためのPOST(POST to append)と状態遷移のためのPOST(POST for transition)もまた、ひとつのResourceObjectに対するルーティングで解決できると思います。

**Comment by ritalin** [comment]
HttpMethodParams.get() だけで済むかと思いましたが、AbstractRequestでGET, POST, PUT, PATCH, DELETE, HEAD, OPTIONSに制限されていて、任意のメソッドを通すことはできないのですね。
この制限を除外するのもどうかとは思うので、この案は見なかったことにしてください。

 個人利用としてHttpMethodParamsや AbstractRequestを差し替えて使うことにします

**Comment by koriym** [comment]
@ritalin もし`CRUD`をリソースにマッチさせるならAOPで行うのがいいと思いますがどうでしょうか？

**Comment by ritalin** [comment]
「AOPで」というのがどのタイミングのことなんかわからないですが、
Request->Invoke()にAOPで差し込み、たとえばコレクションリソースを取得する場合、その場所で、リクエストのメソッドを Get から GetList に置き換るということでしょうか？

**Comment by ritalin** [comment]
現在やりたいことが、例えば
- /foo/animalsで全てのanimalリソースをコレクションとして取得
- /foo/animals/10 でId = 10のanimalリソースを取得

というようなことです。

そして、できることならコレクションと要素の取得はひとつのResourceObjectからにしたいです。
（一つのリソース表現の構築を複数のResourceObjectで行った方が良い場合は、もちろんそうします）

これをAOPだけでどのように解決するのか、私にはその手段が思い浮かびません。

**Comment by koriym** [comment]
一例ですが例えば

インタセプターでは`ResourceObject`のメソッドを呼ばないようにして、自身のつくった`/foo/animals` / `/foo/anilmals/10`を出し分けるドメインモデルをコールします。インターセプターはドメインモデルから受け取ったデータを元`ResourceObject`の`$body`にコピーした`ResourceObject`を返します。

もしmedia typeに`application/vnd.collection+json`を使うなら要素もアノテーションで指定してやればよいと思います。

``` php
/**
 * @CollectionJon(href=...)　// collection+jsonの要素のヒントなど
 */
public function onGet()
{
 // 空
}
```

**Comment by ritalin** [comment]
AOPによるメソッドマッチング、雑に作ってみた。
標準でこうゆうの欲しいです。
https://github.com/ritalin/bear-resource-delegate

**Comment by koriym** [comment]
AOPによるプロキシー例は他にも`Ray.FakeModule`があります。
https://github.com/shingo-kumagai/Ray.FakeModule
