### ISSUE TITLE
No cleanup of buffer files for CLI query passing

### ISSUE THREAD

**Issue by ghost** [bearsunday/BEAR.Package#223]
https://github.com/bearsunday/BEAR.Package/blob/1.x/src/Context/CliModule.php#L26

This temporary file is never removed even after program finished.
So dumps eat up the system `/tmp` directory.
Is this behavior by design and do we need to remove them manually?

```
$ ls -la /tmp
-rw-------  1 user   users        10 Dec 15 14:34 stdin-3895891575FGGRWR
-rw-------  1 user   users         0 Dec 15 14:33 stdin-3895891575HK9600
-rw-------  1 user   users         0 Dec 15 14:33 stdin-3895891575SYzB6D
-rw-------  1 user   users         0 Dec 15 14:32 stdin-3895891575JSz6EW
-rw-------  1 user   users         0 Dec 15 14:32 stdin-3895891575MBP8rv
```

I expect the framework clean them up whenever they're no longer used.
I have no idea when to do. I just thought of a ugly-and-hacky way:

```diff
  $stdIn = tempnam(sys_get_temp_dir(), 'stdin-' . crc32(__FILE__));
+ register_shutdown_function(
+    function () use ($stdIn) { 
+        file_exists($stdIn) && unlink($stdIn);
+    }
+);
```

Are there any ideal ways for the cleanup?

Thank you,

**Comment by koriym** [comment]
It's not our job but `tmpwatch` job ?
http://www.itmedia.co.jp/help/tips/linux/l0609.html

**Comment by koriym** [comment]
@sosuke-ito ping

**Comment by ghost** [comment]
I believe this issue is fixed now. ( from [v1.1.1](https://github.com/bearsunday/BEAR.Package/releases/tag/1.1.1) on )
@koriym Thank you for your cooperation!

**Comment by koriym** [comment]
@sosuke-ito maybe we need testing code for this ?

**Comment by ghost** [comment]
@koriym Oh, Indeed. I'll work on it soon so that coverage be good enough.

**Comment by koriym** [comment]
I thought its only for development, But OK we "hard way" :)

**Comment by ghost** [comment]
Testing code for this issue is now added in #228.
I believe it's working properly but I keep an eye on this. Thank you.
