### ISSUE TITLE
Content-Type が `application/json` の際にinvalidなjsonを送信するとTypeErrorとなる

### ISSUE THREAD

**Issue by kalibora** [bearsunday/BEAR.Package#258]
Content-Type が `application/json` の際に
Bodyを空にするなど invalid な json を送信すると TypeError となるようです。

どのように振る舞うのがベターかはわからないのですが、
HTTPのレスポンスコードとしては4xx系のコードを投げるのが良いかと思っています。
その際に TypeError を Catch するのは乱暴なので、HttpMethodParams でエラーハンドリングして
なにがしかの例外を投げるのが良いかなと思っていますが、いかがでしょうか。

再現コードは下記に置きました。
https://github.com/bearsunday/BEAR.Package/compare/1.x...kalibora:empty-json?expand=1

**Comment by koriym** [comment]
ありがとうございます！後で見ますね

**Comment by koriym** [comment]
json_decodeのエラーをキャッチして`JsonDecodeException`例外とかにしましょうか？

**Comment by kalibora** [comment]
そうなると私的にはとてもありがたいです。

**Comment by koriym** [comment]
ユーザー目線で`InvalidJsonException`の方がいいですね

**Comment by kalibora** [comment]
なるほど。確かにそちらの方が catch する側で自然に感じます。

**Comment by koriym** [comment]
https://github.com/bearsunday/BEAR.Package/pull/259
@kalibora レビューしてもらっていいでしょうか？

**Comment by koriym** [comment]
こんな感じの実装も見るんですが`json_last_error()`でいいような

```php

    public static function decode($json)
    {
        set_error_handler(function () use ($json) {
            throw new JsonDecodeException($json);
        });
        $value = json_decode($json, true);
        if (false === $value) {
            throw new JsonDecodeException($json);
        }
        restore_error_handler();
        return $value;
    }
```

**Comment by kalibora** [comment]
> @kalibora レビューしてもらっていいでしょうか？

見させていただきます！

**Comment by kalibora** [comment]
#259 で対応されたのでクローズします。

**Comment by koriym** [comment]
[1.7.2](https://github.com/bearsunday/BEAR.Package/releases/tag/1.7.2)でリリースしました
