### ISSUE TITLE
Don't do `require` for autoloaded classes.

### ISSUE THREAD

**Issue by sasezaki** [bearsunday/BEAR.Package#300]
currently, Compiler generate with
```
"require %s';\n"
```

should use `require_once`.

**Comment by koriym** [comment]
Why do you think so? `require` is faster.

**Comment by sasezaki** [comment]
I wouldn't expect call `require` statement on named `autoload.php`.

From another point of view, `autoload.php` naming, a lot of developers will be cofused, I think.

could you consider adding comment in `autoload.php` that purpose what.

**Comment by koriym** [comment]
> I wouldn't expect call require statement on named autoload.php.

1) 'autoload' eventually, just "predicted" 'require' statements are listed before "autoload" to avoid unnecessarily file search and load the class file which consumes a lot of bootstrap time for nothing repeatedly.

2) Clarify what values are expected to add with  `_once` please?

**Comment by sasezaki** [comment]
I mean if named `autoload.php`, I expect "if class not loading, class definition file loading" as **PHP's autoload** behavior.

I suggest rename Compiler's generate `autoload.php` to `pre_class_load.php` to be clear.
( and remove
`$fies .= "require __DIR__ . '/vendor/autoload.php';" . PHP_EOL;`)

And, In BEAR.Skeleton's  `public/index.php`.
change like below.
```php
<?php
require dirname(__DIR__) . '/pre_class_load.php';
require dirname(__DIR__) . '/vendor/autoload.php';
exit((require dirname(__DIR__) . '/bootstrap.php')(PHP_SAPI === 'cli-server' ? 'hal-app' : 'prod-hal-app'));
```

**Comment by koriym** [comment]
Thanks, Clarified. It would be nice if you put those lines in the first post, "Don't" & "Should" without reasoning bring us nowhere.

The user really does not need to care what's in "./autoload.php". "if class not loading, class definition file loading" was supported. Usage is the same but with performance.

**Comment by koriym** [comment]
I still see your change add little value and seems discussion is enough. I'm going to close this issue. Thank you for your interest.

**Comment by sasezaki** [comment]
Sorry for the lack of explanation at first post.

"should use require_once" was mistaken.
"should replace `if (!class_exists()) require`" was better.

**Comment by koriym** [comment]
Still feel same. Don’t get me wrong, I should note I like your deep inspection and appreciate with your concern with our project.
