### ISSUE TITLE
Need Description for Compiler::scanClass

### ISSUE THREAD

**Issue by sasezaki** [bearsunday/BEAR.Package#301]
at https://github.com/bearsunday/BEAR.Package/blob/1.9.3/src/Compiler.php#L146

I can't understand why this method named as `isMagicMethod`,  and skiped.

Anyone explain where these methods `['__sleep', '__wakeup', 'offsetGet', 'offsetSet', 'offsetExists', 'offsetUnset', 'count', 'ksort', 'asort', 'jsonSerialize']` came from ?

**Comment by koriym** [comment]
マジックメソッド
https://www.php.net/manual/ja/language.oop5.magic.php

Those methods are not called by the user, Skipped because of no annotations and no named parameters are expected.

**Comment by koriym** [comment]
Sorry for the very late response.
