### ISSUE TITLE
'Dev' mode reload error.

### ISSUE THREAD

**Issue by zukimochi** [bearsunday/BEAR.Package#31]
If you start with 'Dev' mode the Web server,
public/web.php

``` php
$mode = 'Dev';
```

``` shell
% php -S localhost:8088 web.php
```

The first request succeeds, but the second fail.

Probably 'src/Bear/Resource/Devinvoker.php' is related to this error. 
It works when using the "Invoker" instead of "Devinvoker".

src/BEAR/Package/Module/Resource/DevResourceModule.php

``` php
protected function configure()
    {
        // DBAL debug
        $this->bind('Doctrine\DBAL\Logging\SQLLogger')->to('Doctrine\DBAL\Logging\DebugStack')->in(Scope::SINGLETON);
        // Common debug
        //$this->bind('BEAR\Resource\InvokerInterface')->to('BEAR\Resource\DevInvoker')->in(Scope::SINGLETON);
        $this->bind('BEAR\Resource\InvokerInterface')->to('BEAR\Resource\Invoker')->in(Scope::SINGLETON);
        $this->install(new ProvideModule\ResourceView\DevRendererModule($this));
        $this->installDevLogger();
    }
```

英語自信ないので日本語で補足します。
'Dev'モードの時、どのページでもいいので一旦表示させたあとにリロードするとwebサーバーがsegmentation faultで落ちてしまいます。
Invorkerを使うようにすると普通に動くので、DevInvokerが関係していそう、というところまでは調べたのですがその先が追えていません。

**Comment by koriym** [comment]
報告ありがとうございます！しかし再現できないです。
core dumpで何のメッセージで落ちてるか確認できるでしょうか？

**Comment by koriym** [comment]
経験上PHPでの大抵のsegmentation faultはextensionです。xhprof/xdebug/apc/pdo この辺りを一回外して試してもらえないでしょうか？

**Comment by zukimochi** [comment]
すいません。こちらの環境の問題でした。
homebrewで入れたphp5.4がおかしかった(?)ようです。

```
% curl -s http://php-osx.liip.ch/install.sh | bash -s 5.4
```

これで入れなおしたら動くようになりました。

お騒がせしました。

**Comment by koriym** [comment]
もしかしたら原因はそのphpについてたext、あるいはdevということはpdo-sql使ってるのでもしやその辺りか... いずれにせよエラーになってほしいですね。

**Comment by koriym** [comment]
A questioner solved the problem by self with switching PHP. Homebrew PHP produced unexceptional segmentation fault but 'php-osx' PHP has no problem. Weird.
