### ISSUE TITLE
php api.php get app://self/blog/posts するとPASSWORDが''な状態でDB接続エラー

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#39]
bin/env.php ではDB接続問題ないのに、
php api.php get app://self/blog/posts するとPASSWORDが''な状態でDB接続エラーになる。

https://twitter.com/atakig/status/328501686538752001

**Comment by koriym** [comment]
DI束縛の確認方法

1) webで
`/dev/di/` にアクセスするとDIの束縛が分かります。

```
bind('')->annotatedWith('master_db')->
bind('')->annotatedWith('slave_db')->
```

2) プログラム中で
$injectorをechoすると束縛表示されます

web.phpなどで

``` php
echo $app->injector;
```

**Comment by koriym** [comment]
設定の確認：

`config/prod.php` でDB接続情報を確認します。（Devモードでは`dev.php`も）

対処：

ここはユーザースクリプトなので自由に変更できます。環境変数からの取得を推奨しますが、ハードコードする事も可能です。

**Comment by koriym** [comment]
https://code.google.com/p/bearsunday/wiki/install

この説明ではSLAVEをオプションとしてますが、ソースでは

https://github.com/koriym/BEAR.Package/blob/4adfe872b741ddcd93cfc30257610147a5d37c63/apps/Sandbox/config/prod.php

必須（なければroot/'')、これが問題でしょうか。
SLAVEを指定するか、prod.phpでもし指定していなかったらmasterのものと同じものを使うというコードにすれば解決しますでしょうか。@atakig

**Comment by atakig** [comment]
環境変数の BEAR_DB_PASSWORD_SLAVE に(mySQLの)root@localhostのパスワードを設定すれば、
繋がりました。

> SLAVEを指定するか、prod.phpでもし指定していなかったらmasterのものと同じものを使うという
> コードにすれば解決しますでしょうか。

環境変数の BEAR_DB_PASSWORD_SLAVE を削除した後、korlym氏の上記ロジックで繋がりましたので、
問題ないと思われます。

**Comment by koriym** [comment]
フィードバックありがとうございました。
反映します。

ドキュメントとコードの品質向上に繋がりました。
これからも宜しくお願いします。

**Comment by koriym** [comment]
http://code.google.com/p/bearsunday/wiki/install

ドキュメントを修正してslaveの設定を必須にしました。
