### ISSUE TITLE
Notice: Illegal member variable name in /path/to//Ray/Di/Injector.php

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#40]
https://github.com/koriym/BEAR.Sunday/issues/27#issuecomment-17218680

**Comment by koriym** [comment]
今developブランチの最新版で同じ現象が出る様になって困ってます。
xdebug.collect_paramsが"1"でも駄目で"0"にするとnoticeが出なくなります。 

@gusagi

**Comment by gusagi** [comment]
@koriym 反応が遅くなってしまいすみません。
私の環境でも動作確認してみました。

> 今developブランチの最新版で同じ現象が出る様になって困ってます。
> xdebug.collect_paramsが"1"でも駄目で"0"にするとnoticeが出なくなります。

ハッシュ"31ff789"を始め、このissueに紐付いている各コミットの状態にして動作確認してみましたが、私の環境だとinstance.php内で指定しているxdebug.collect_paramsの値が"2"でも問題ありませんでした。
ただ、php.iniで設定値を3以上にすると #27 のエラーが出たので、私の環境だとini_set() 関数で設定が変更できていないのかも知れません。。。
あまり参考にならなそうですが、とりあえず報告させて頂きました。

**Comment by koriym** [comment]
現在の保守的な設定ではまず大丈夫かと思います。xdebugの方へのissueも上げた方がいいのでしょうが、再現コードがなかなか難しいですね...
