### ISSUE TITLE
SQL Mapper

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#46]
## Overview

Sql map library like iBatis(JAVA) or Prado(PHP)
- http://ja.wikipedia.org/wiki/IBATIS
- http://dozo.matrix.jp/framework/prado/database/sqlmap

**Comment by MugeSo** [comment]
Is this mean mapping SQL to Resource?

**Comment by koriym** [comment]
リソースのアノテーションでSQLのIDを指定すると、リソースとSQLがマップされるようなものです。

SQL can be mapped through @Sql annotation in resource object.
