### ISSUE TITLE
Application directory structure

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#65]
Current application structure

```
.
├── App.php
├── Interceptor
├── Module
├── Params
├── Resource
├── build
├── config
├── data
├── http
├── phpunit.xml.dist
├── public
├── scripts
└── tests

```

**problem**
- mixed classes and scripts,
- difficult to apply phpmd and phpcs (no /src folder)
- public/ folder has web resource as well as php scripts
- too much item ?
- no qa tool config files
- `config` was used by Module, but hard to find how.
- `http` was used only application script, but also hard to find how. no needs at top ?
- _files_ which used by something inside application should not listed on top. it should include by owner.

**Comment by koriym** [comment]
what about this ?
![2013-09-21 15 36 02](https://f.cloud.github.com/assets/529021/1185160/2a3bc9d2-2288-11e3-9434-bf33c6f4db0f.png)
- put the folder right place, then sym link if you want to place on top directory.
  for example, config was used in Module, then linked from there to top.
- var/vendor has vendor _extension_  module such as smarty/twig plugin/filter.
- /var/www has one index.php sym linked from scripts/app
- all scripts are put in scripts/ folder
- bin/*.php is also script but not by php, this was run by console operation  or cron job.
- all class files (Resource / Module / Interceptors) are in /src folder, for make qa tools handling easy also follow PSR0.

**Comment by mackstar** [comment]
I think the new app layout is much better and replicates further the layout of BEAR.Package itself.

A really good improvement. 

A few questions/comments I have are:
- The directory names `bin`and `scripts` can be easy to get mixed up. Is there something we can name them (particularly scripts) to make sure the different role is clear.
  - Would `bootstrap` be a better word to describe what it is doing?
  - Would `autoload.php` be a a better file name than `load.php`?
  - Could scripts/app be renamed to `environments` or `runtimes` etc?
  - Inside `var/www` there is an assets directory. We should either place all js/css/img assets in here, or remove the directory and have `var/www/js`, `var/www/css`, `var/www/img` directories.
- Error files 4-500's are still flat PHP files, is there a way to better integrate them so that they may be better integrated with chosen template engine and maybe even have their own attached resource?
- Does this make Apache/Nginx configuration more complicated? Or does this single `/var/www` has one index.php symlink handle this? - I think it does doesn't it.
- Does the extra symlinking create more work when creating the app? Can we add this in the build file?
- I notice you still use Ant as a build tool - I like ant. (But is it worth considering Phing for per php-ers?).

**Comment by koriym** [comment]
You can check the detail of the structure here. 詳しくはここで見れます。
https://github.com/koriym/BEAR.Package/tree/feature/new_layout

**Comment by remore** [comment]
Agree with @mackstar ,that's much better folder structure. 

A few points from me. First point is, to have both `bin/` and `scripts/` folder at top level at the same time looks a bit confusing to me too. In fact, "scripts" is too generic naming to understand what can be done easily. Why not move `scripts/` folder to somewhere under `src/` ?

The other point I'm feeling a bit awkward is `var/` folder. Can't get what to do about them easily. I prefer move entire `var/` folder under `src/`.

**Comment by hidenorigoto** [comment]
New App layout is easy to understand.

I'm confused a little by the word `Application` for two different layers (`Sandbox` is an application and `scripts/app/prod.php` is an application because of its directory name).

How about `context` instead of `app` ? - (ex. `scripts/context/prod.php`)

**Comment by koriym** [comment]
wow @mackstar , thanks a lot of thoughtful comments !

I would like to answer inline comment by comment.

> Would bootstrap be a better word to describe what it is doing?

instated of `scripts` ? make sense and also telling its not for the program, not by user. its good idea.
but what about this ? is it OK ?

```
$app = /path/to/Sandbox/scripts/instance.php;
// become
$app = /path/to/Sandbox/bootstrap/instance.php;
```

> Would autoload.php be a a better file name than load.php?

`load.php` also include _manual loading_ (annotation / function), but its important people's recognition more than accuracy, good idea. I will take it.

> Could scripts/app be renamed to environments or runtimes etc?

I thought we can explain like this.
- `Application` object has only one role. It holds tools you can use in **application script** (scripts/app) in public property.
- You can know what tools you can use in it by application object not by documentation. 

but  `environments` / `runtimes` can describe you can configure application script by `environments`. it make sense. Or what about `contexts` ?

> remove the directory and have var/www/js, var/www/css, var/www/img directories.
> totally agreed. `assets` is by Twitter bootstrap, and other js/css/img is by application. What is the good way to mixed up ?
> 
> Error files 4-500's are still flat PHP files, is there a way to better integrate them so that they may be better integrated with chosen template engine and maybe even have their own attached resource?

this should no be problem at all. To produce the page using template engine is fairly easy like...

``` php
$response = $app->resource->get->uri('page://self/error')->withQuery(['error' => 404])->eager->request();
// output
foreach ($response->headers as $header) {
    header($header);
}
echo $response->body . PHP_EOL;
```

you can write this code either var/http/404.php or `prod.php`. you can mix static / plain / bear /or even other fw produce code by error number.

The point is that the application describe how to handle exception _not by built-in exception handler in framework._　maybe I put one example code for particular code to guide to this is not fixed structure ?

> Nginx configuration

no idea !  please help !!

> Does the extra symlinking create more work when creating the app? 

no worry. git can have a sym link. Just in the case when you think its too deep. (`src/Sandbox/Resource` can be `Resource` on top) this PSR0 rule can be changed next PSR-X autoloader.

> I notice you still use Ant as a build tool - I like ant.

no need to setup for OSX. its good. also it seems like most popular ? no ?

**Comment by koriym** [comment]
@remore `bin` is for operator / cron job. User can use directly. `scripts` is for the program. and it can not moved be src/ which holds only class files.

I use `scripts/` folder for all Ray / BEAR software. but seems better to change for the application.  any idea ?

**Comment by koriym** [comment]
@hidenorigoto already mentioned why "app". but I found it ts not great name. 
`context` (or `contexts`) is same idea as mine. But I would like to ask @mackstar again. We can say its **application context script** instead of former "application script*.

I would like to ask @mackstar again, `runtime` still sounds better ? I know you have more sense with the word more than us :-)

**Comment by koriym** [comment]
new proposal

top level:
![2013-09-21 18 28 46](https://f.cloud.github.com/assets/529021/1185357/46a3c288-22a0-11e3-98e6-b4640e0e590e.png)

detail:
![2013-09-21 18 27 56](https://f.cloud.github.com/assets/529021/1185356/28a8de1c-22a0-11e3-9a7c-3009aff7f717.png)

Impression ? any new thought ?  @mackstar @remore @hidenorigoto

**Comment by koriym** [comment]
`app` is widely used for entire project in many frameworks. Now i understand !　今分かりました！！ @hidenorigoto @mackstar

**Comment by koriym** [comment]
ping @iteman  @zukimochi @jingu @kumamidori @nekoget @tdakak @gusagi @rsky @ryo88c @nishigori

Please allow me to send you spam ping  ! the first and last one, only one time in this project. 
I just wanted to hear your thoughts because this layout is for users.
すいません意見を聞きたかったのです。一回だけのspam pingということで許して下さい＞＜

**Comment by koriym** [comment]
ping @ha1t @brtriver @hirak @fivestar @tanakahisateru

**Comment by mackstar** [comment]
I like the name contexts sounds a great idea.

**Comment by hidenorigoto** [comment]
New structure is much better than I think.
`bootstrap` and `context` are good names.

Another point I found is an asymmetric structure between `bootstrap/instance.php` and `bootstrap/develop/instance.php`.
How about `bootstrap/instance/prod.php` and `bootstrap/instance/dev.php` ?

**Comment by koriym** [comment]
@mackstar `config` seems popular more than `configs`, so is `context` a way to go ?

**Comment by koriym** [comment]
@hidenorigoto it can't be. `instance.php` supply instance like this.

``` php
$instance = require '/path/to/instance.php';
```

this usage is widely discovered in Aura framework. and I just follow it. 
Context files are script file supply no instance, just work as plain script file. There are no scopes and no objects. The statement was executed from the top to down like as shell file. that's it.

**Comment by mackstar** [comment]
@koriym `configs` is un-natural so seems wrong, there is usually a single configuration containing multiple options.
- 1 configuration
- multiple configuration options.
  
  `contexts` however does sound natural and is a good way of describing that there are multiple contexts which are available. This is the difference. `contexts` sounds more natural for me and seems to describe the role of the directory better.
- multiple contexts

**Comment by mackstar** [comment]
I actually like the `var` directory despite other peoples confusion. It seems clear to me.

**Comment by mackstar** [comment]
Big thanks to @hidenorigoto and @koriym for typing in English. お疲れさまです！

**Comment by mackstar** [comment]
I still am unsure of `load.php` is `loading.php` more sensible?

**Comment by koriym** [comment]
リチャード先生ありがとうございます！
@mackstar , your great explanation leads us better English speaker. thanks for the lesson.

Hope everybody in BEAR.Sunday issue can enjoy conversation even with minimum broken English but have a great communication.

**Comment by koriym** [comment]
@remore about `var/`

In BEAR.Saturday I use data/ for tmp/ and logs/
- data/tmp 
- data/log

`data` ? everything is data. it sounds `$value` in php. it explains nothing. I need something better.

Not in src/.  its for the source code as described. It must class file which can be load with PSR0 mechanism.

I found this: http://www.linfo.org/var.html It helps to get clue ?
-  "it is not shared over a network with other computers" (let's say, its application specific function / data inside)
-  " the various sub directories" would be expected.

**Comment by kumamidori** [comment]
to have /var/vendor folder looks a bit confusing to me.
/var/vendor フォルダが、私には少し分かりにくく感じました。

Why not move /vendor folder to top?
トップレベルに置かなかったのは何か理由があるのでしょうかね。

by Sunday beginner.
初心者なので全然分かっていないままコメントしています。すみません。

**Comment by koriym** [comment]
@kumamidori さんコメントありがとうございます。

図に出してるように`var/vendor`はcomposerの`vendor`ディレクトリではなくて、`vendor`ライブラリが使用するファイルです。例えばフレームワークが依存する`vendor/smarty`はフレームワークの`plugin`フォルダとアプリケーションの`var/vendor`にアプリケーション用の`plugin`フォルダを持ちます。

これをトップに置いてしまえば問題が出てしまいます。
- composerのvendorディレクトリに見える
- アプリケーションがcomposerを使った時に衝突する

まずアプリケーションを作って、composerで`vendor/` にBEAR.Packageをインストールすることができます。Saturdayでも同じでしたが、フレームワークを主体にしてアプリケーションをインストールするか（複数アプリケーション）、アプリケーションを主体にしてフレームワークをインストール（１対１）するかの違いです。

**Comment by koriym** [comment]
@kumamidori 
`var/vendor/smarty`の代わりに `var/smarty/` でもいいかも知れませんね。
どうでしょうか

**Comment by remore** [comment]
@koriym Ha! I just backed from weekend contrabass lesson. I have read all the comments, and liked the idea to use `bootstrap/` instead of `scripts/`.

However, current `var/` folder still looks awkward at some point. According to FHS, (I refered the FHS2.3 found at this site: http://www.pathname.com/fhs/ )

> /var contains variable data files. This includes spool directories and files, administrative and logging data, and transient and temporary files

This definition makes sense to me. For example, `var/lock`, `var/log` or `var/tmp` are the kind of name I can easily imagine and feel fine.

As to BEAR.Package's current `var/` folder idea, following naming sounds understandable to me while `var/vendor` is not.
- `var/log`
- `var/tmp`
- `var/www`
- `var/http`(note that `var/response_template` or `var/lib/response_template` can be better alternative, as `http` is be too big terminology to explain what actually `var/http` folder does)

Since `var/vendor` contains optional libraries, it can be moved under `/opt`, `/var/opt` etc if I think of FHS.

I don't think FHS is convincible to all the people here. Some of Ops/Administrator like me might feel the same but may not be majority. I don't think to use `var/opt` is apparently better than `var/vendor`, but what is sure is I feel a bit awkward to hear `var/vendor` and `var/http`.

I just hope my comments helps. @koriym's current idea should be ok if most of people here can understand easy enough.

**Comment by koriym** [comment]
Welcome back ! weekend contrabass sounds nice. You must had a great time !

Also good to hear from the specialist.
Let's summarize. We have ...
- http response files
- vendor related files. but no matter under`vendor` or not. `var/libs/smarty` ? or `var/smarty` too wild ?
- user libraries (not supplied by packagist)
- cvs / json  / data files

and maybe some more. the original idea is we have a single one big directory which can holds anything extra. it should not be autoload-enable-class-file.

I would like to hear more your comment. thanks.

**Comment by koriym** [comment]
FHS
- `bin`
- `build`
- `boot`
- `etc`
- `var`

BEAR.Sunday app
- `bin`
- `build`
- **`bootstrap`**
- **`config`**
- `var`

`*bootstrap` and `config` are widely recognised for web application directory layout terminology. It's nice idea  `bootstrap` as a directory name. thanks @mackstar

**Comment by kumamidori** [comment]
@koriym 解説レスありがとうございます。
初歩的な質問ですみません。１点分からなかったことがありました。

/var/vendor/ の下にフレームワーク用のcomposer.jsonがあるということですかね？
フレームワーク用の依存管理、同梱されているライブラリのバージョン番号を見る場所も何かしら必要ですよね。

**Comment by koriym** [comment]
> /var/vendor/ の下にFW用のcomposer.jsonがあるのですかね？

無いです。
`/var/vendor/`はBEAR.Packageの`vendor`のアプリケーション個別のファイルが入ります。例えばテンプレートエンジンでフレームワーク`plugin`とは別にそのアプリケーションだけの`plugin`が入ります。composerと直接の関係がありません。

> フレームワーク用依存管理(ライブラリのバージョン番号を見る場所)も必要ですよね。

現在はフレームワークからアプリケーションを作っていますが、アプリケーションからフレームワークをインストールすることができます。

アプリケーションフォルダの中から下記のコマンドでインストールできます。

``` bash
composer require bear/framework:*
```

/path/to/app/vendor/ 下にbear/package , sunday ... と入り`composer.lock`ができます。

**Comment by kumamidori** [comment]
@koriym 理解いたしました！

> var/vendor/smartyの代わりに var/smarty/ でもいいかも知れませんね。
> どうでしょうか

フォルダが増えたときに混乱しそうなので、
直下に置くよりも、何らか１つにまとまっている方が（var/vendor/smarty or var/libs/smarty or etc..）
良さそうに思いました。

**Comment by NEKOGET** [comment]
私も1つにまとまっている方が好きです。
var/vendor/smarty と var/smarty/ なら var/vendor/smarty を押したいです。

**Comment by koriym** [comment]
![2013-09-22 11 12 14](https://f.cloud.github.com/assets/529021/1186868/85f54542-232c-11e3-82a0-ecc6585b8321.png)

`var/vendor/`がcomposerと混乱してしまうのなら & 他も何でも`/var/lib/`に？

**Comment by koriym** [comment]
proposal updated
![2013-09-23 9 30 39](https://f.cloud.github.com/assets/529021/1188767/759b8f10-23e7-11e3-8db0-c7251b1ec825.png)

**Comment by koriym** [comment]
このレイアウトで0.9.0としてリリースしました。良かったら動作確認報告よろしくお願いします。
