### ISSUE TITLE
PHP Notice:  Undefined property: BEAR\Resource\Logger::$logs

### ISSUE THREAD

**Issue by koriym** [bearsunday/BEAR.Package#74]
PHP Notice:  Undefined property: BEAR\Resource\Logger::$logs in /bear/vendor/bear/resource/src/BEAR/Resource/Logger.php on line 83

**Comment by hidenorigoto** [comment]
インストール後に表示される環境チェックとしては、以下になります。

```
== Required ==
 OK PHP:5.4.20
 OK Vendor install
== Optional ==
 OK APC:3.1.13
 OK DB connect(root/)
== Develop ===
 NG xhprof: ()
 NG Xdebug:
 OK PDO-Sqlite: 1.0.1

BEAR.Sunday env check:  OK
```

インストール処理の最後、コンパイルが実行され、その最後のアプリケーション終了時に表題の警告が必ず発生します。
また、Sandboxアプリケーションのdev.phpでは警告が表示されませんが、api.phpでは同様の警告になります。

以下は推測です。
- CacheInjectorのインスタンス作成時に、キャッシュ内のオブジェクトをClosureのuseに指定して終了処理を登録している
- CacheInjectorの終了処理より前に、キャッシュ内オブジェクトのシリアライズが行われる。この時、Loggerで次のコードが呼び出される

```
    unset($this->logs);
```
- CacheInjectorの終了処理経由で、Loggerのwrite()が呼ばれるが、すでにLoggerの$logsはunset()されているため、警告となる

**Comment by koriym** [comment]
報告ありがとうございます。`unset($this->logs);`が問題なのはその通りだと思います。

**Comment by koriym** [comment]
WIP

**Comment by koriym** [comment]
fixed #???
