### ISSUE TITLE
Compiled preload file has error on Sandbox app

### ISSUE THREAD

**Issue by MugeSo** [bearsunday/BEAR.Package#94]
``` shell
$ php -l var/tmp/preloader/preload.php
PHP Fatal error:  Cannot mix bracketed namespace declarations with unbracketed namespace declarations in var/tmp/preloader/preload.php on line 18071
Errors parsing var/tmp/preloader/preload.php
```

**Comment by koriym** [comment]
I had a different result.

> No syntax errors detected in var/tmp/preloader/preload.php

Also, this is a issue for classpreloader/classpreloader ? 

However, You may avoid this error by `addExclusiveFilter()` to exclude the shown class.
Check the file  `/var/lib/preloader/config.php` on line around 18071 as shown.

**Comment by MugeSo** [comment]
> I had a different result.

It's odd.

I got the broken file when I cloned dev-develop and ran compile script.

line 18071 is:

``` php
namespace {
/**
 * Smarty Internal Plugin Smarty Template Compiler Base
 *
```

ちなみに、完全にクリーンなVMで環境を構築した直後に実行した結果です。(というか、Chefのcookbook作ってたらこの現象に出くわしました)

**Comment by MugeSo** [comment]
https://github.com/webnium/BEAR.Sunday-cookbook

**Comment by koriym** [comment]
confirmed.

**Comment by koriym** [comment]
If you encounter same error again, the east solutions is "just omit that class with `var/lib/preloader/config.php`"

もし同じエラーが違うライブラリの導入後に出たら単純な解決策は「エラーになる読み込みクラスを`var/lib/preloader/config.php`で外す」です。

``` php
 ->addExclusiveFilter('/Smarty_Internal_TemplateCompilerBase/')
```
