### ISSUE TITLE
PHPUnitのsetUpのvisibility

### ISSUE THREAD

**Issue by kumamidori** [bearsunday/BEAR.Package#98]
BEAR.Packageのテストコードで、

public function setUp() になっている箇所と、
protected function setUp() になっている箇所があるのですが、

protected が正しいのでしょうか。そうではなくて、意図的なものでしょうか？
お手すきの際に教えて頂ければと :ram:

**Comment by koriym** [comment]
いや、いい加減なだけです。 protected がいいですかね。

**Comment by kumamidori** [comment]
では今度こちらでPR用意します！ワンライン系ばかりですみません、笑。

**Comment by koriym** [comment]
いやいやとんでもないです。簡単な置換だしすぐ直します。ありがとうございました。
